# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: erc20indexer
description: ERC-20 indexer
networks:
  - id: 534352 # Ethereum Mainnet
    # op: 10, arbitrum: 42161, scroll: 534352, sepolia: 11155111, zksync-era: 324
    # start_block: 124269527 # optimism
    start_block: 8543498 # scroll
    # start_block: 244769593 # arbitrum-one
    # start_block: 6535522 # sepolia
    # start_block: 42154804 # zksync-era
    contracts:
      - name: MerkleDistributorFactory
        abi_file_path: abis/MerkleDistributorFactory.json
        # address: 0x3fD1AB4577b80f184de4E64C980eBA019b6C6D8E # optimism
        address: 0xbB66E0685DE1De517B3a3169f460226b59107A46 # scroll
        # address: 0xA436de894D19Ff26268fCe4350b90fDbb6BB8219 # arbitrum
        # address: 0xb0B8394c1365D0caE674b3254B1e4A19aAEddc5A # sepolia
        # address: 0xbfF99D3Bc98c97AD6486eC114436DeA7D38E063e # zksync-era
        handler: src/EventHandlers.ts
        events:
          - event: DistributorCreated(uint256 total,bytes32 id,string name,string message,address token_address,uint256 number,uint256 duration,address creator,uint256 creation_time, address distributor)
      - name: MerkleDistributor
        abi_file_path: abis/MerkleDistributor.json
        handler: src/EventHandlers.ts
        events:
          - event: Claimed(uint256 index,address account,uint256 amount)
          - event: Refund(address to,uint256 refund_balance)    
